### ISSUE TITLE
[Doc] [7.10] 分析 NimBLE HCI 层的对接方式

### ISSUE THREAD

**Issue by Yanlineng** [Yanlineng/summer#14]
1. 简单描述 NimBLE 层次结构
2. 分析 HCI 层对接接口
3. 分析 RAM 空间对接 HCI 的代码，为后面对接 UART 做参考。

**Comment by Yanlineng** [comment]
BLE蓝牙核心协议（Bluetooth Core）分为 BLE Controller 和 BLE Host 两部分， Controller负责定义RF、Baseband等偏硬件的规范，并在这之上抽象出用于通信的逻辑链路（Logical Link）；Host负责在逻辑链路的基础上，进行更为友好的封装，这样就可以屏蔽掉蓝牙技术的细节，让Bluetooth Application更为方便的使用。

主机控制接口层（Host Controller Interface，简写 HCI）：HCI是可选的，HCI主要用于2颗芯片实现BLE协议栈的场合（一个当作 Host 一个当作 Controller），用来规范两者之间的通信协议和通信命令等。

**Comment by Yanlineng** [comment]
最新版本的代码中，HCI 层的对接实现较旧版本更加简洁了，官方也提供了 transport 层的[介绍文档](https://github.com/Yanlineng/mynewt-nimble/blob/master/nimble/doc/transport.md) ，介绍到可以通过 UART 进行对接。
主要下面这张图已经描述得很清楚了:
+----------+                       +----------+
| cmd pool |                       | evt pool |
+----------+                       +----------+
| acl pool |                       | acl pool |
+----------+                       +----------+
  ||                                       ||
+----+                                   +----+
|    | <--- ble_transport_to_ll_acl ---- |    |
|    | <--- ble_transport_to_ll_evt ---- |    |
| HS |                                   | LL |
|    | ---- ble_transport_to_ll_cmd ---> |    |
|    | ---- ble_transport_to_ll_acl ---> |    |
+----+                                   +----+

**Comment by Yanlineng** [comment]
目前我们项目只需要关注 Host 层，就需要对接好 从 Controller 端接收接口 ble_transport_to_hs_evt  和 ble_transport_to_hs_acl。 以及 向 Controller 发送接口 ble_transport_to_ll_cmd 和   ble_transport_to_ll_acl。
还要了解一下上图中 cmd 、acl 和 evt 消息类型的含义。 
以及消息体的内存组织形式 os_mbuf 也可以稍微了解一下。

**Comment by Yanlineng** [comment]
在 transport/include/transport_impl.h 中可以看到相关接口声明
![image](https://user-images.githubusercontent.com/77085567/176466640-22ce8b50-9b12-44ac-af7f-3161d4e1a1f5.png)
这里从头文件名字，以及接口声明方式都能看出来是我们需要实现对接的接口。后面的工作主要就是 用 RT-Thread UART 来实现这些接口，完善 HCI 层。

**Comment by Yanlineng** [comment]
分析官方源码中 nimble/transport/uart/src/hci_uart.h 这里给我们对接 UART 做了一个例子，就着这个例程实现来分析一下如何实际对接。分析源码的大概脉络：
首先找到熟悉的接口，代码中实现了 ble_transport_to_hs_acl_impl 以及 ble_transport_to_hs_acl_impl ， 且没有实现其他的 impl 接口，在这里我初步感觉，这是写的 Controller 端的 hci 层代码。

**Comment by Yanlineng** [comment]
ble_transport_to_hs_acl_impl 和 ble_transport_to_hs_acl_impl 中基本上就是 使用 uart 向 host 发送数据包，涉及到某个板子uart 发送数据的具体细节，这里不过多关注。

**Comment by Yanlineng** [comment]
再看一下，Controller 如何从对端接收包，这里看到了这个 static int hci_uart_rx_char(void *arg, uint8_t data) 函数，这个函数被 hal_uart 注册为了uart接收回调函数，每次接收一个字节自动调用一次，接收到的字符使用 hci_h4_sm_rx() 接口进行了接收。
![image](https://user-images.githubusercontent.com/77085567/176691897-0f3e30dc-7a95-4103-86f1-61d4fdbe8b8e.png)

hci_h4_sm_rx() 函数定义在 transport/common/hci_h4/src/hci_h4.c 源码文件下，是关于 H4 的一个函数，并且接收字符后，有一个组帧判断的过程。初步看了一下 函数声明，是 hci_h4 的一个接口
![image](https://user-images.githubusercontent.com/77085567/176692579-0ae4f33b-fa3a-47d0-9773-41de8e983fa7.png)

再看一下 其他地方关于 hci_h4_sm 的地方，在初始化中看到调用了 hci_h4_sm_init，在参数中有一些关键的东西。
![image](https://user-images.githubusercontent.com/77085567/176692084-ad527f3f-b87b-4bab-95d8-8471febdc5a9.png)

这里比较关键的应该是 hci_uart_frame_cb 函数，这明显是一个回调函数的注册，并且结合之前 hci_h4_sm_rx() 以及 hci_h4.h 声明的一些接口，大概能猜到是完成组帧后的回调函数。

这个  hci_uart_frame_cb 在代码中也实现了，看一下实现：
![image](https://user-images.githubusercontent.com/77085567/176693543-3d59721d-f278-4e29-a412-60e0ac128c10.png)

基本上是对一个完整的 HCI 包的处理，根据 不同的类型 使用 ble_transport_to_ll_cmd 和 ble_transport_to_ll_acl 传输给 Link Layer 层(这是 controller 上的一个层次，更加确定这是Controller 上的 HCI 层实现 )。

**Comment by Yanlineng** [comment]
看到这里，大概脉络应该已经捋清楚了。
首先这是一个 Controller 上的 UART HCI 层对接实现：
1. 向 Host 发送 HCI 包：主要通过显式实现  ble_transport_to_hs_evt_impl 以及 ble_transport_to_hs_acl_impl 接口实现，具体何时被调用，协议栈已经自动处理好。
2. 从 Host 接收 HCI 包：主要是使用的 hci_h4 中的组包接口，hci_h4_sm 即一个组包的状态机实例，通过 hci_h4_sm_rx() 接收 uart 接收到的字符，在判断 hci 包完整接收时调用提前注册好的 回调函数 hci_h4_frame_cb 。 hci_h4_frame_cb 里则实现了将 uart 接收到的包传递给 LL 层，进而 Controller 可以对 Host 传下来的命令或数据做出响应动作。

**Comment by Yanlineng** [comment]
看到这里，大概脉络应该已经捋清楚了。
首先这是一个 Controller 上的 UART HCI 层对接实现：
1. 向 Host 发送 HCI 包：主要通过显式实现  ble_transport_to_hs_evt_impl 以及 ble_transport_to_hs_acl_impl 接口实现，具体何时被调用，协议栈已经自动处理好。
2. 从 Host 接收 HCI 包：主要是使用的 hci_h4 中的组包接口，hci_h4_sm 即一个组包的状态机实例，通过 hci_h4_sm_rx() 接收 uart 接收到的字符，在判断 hci 包完整接收时调用提前注册好的 回调函数 hci_h4_frame_cb 。 hci_h4_frame_cb 里则实现了将 uart 接收到的包传递给 LL 层，进而 Controller 可以对 Host 传下来的命令或数据做出响应动作。

**Comment by Yanlineng** [comment]
一开始没有看懂 hci_h4_sm 有什么用，后面结合 hci_uart.c 中的使用，以及对 hci_h4_sm 相关接口源码的分析，大概明白了这是一个小的状态机，用于判断逐段接收数据时的包状态。hci_h4_sm 其实是官方提供的一个类似保证包完整性的东西，用于判断一帧完整的 HCI 数据包，并且提供组包完成回调函数的机制。也一定程度上能保证 UART 传输时，可能遇到的一些错误的包组合吧，以免发生传递错误 HCI 包的问题。

**Comment by Yanlineng** [comment]
一开始没有看懂 hci_h4_sm 有什么用，后面结合 hci_uart.c 中的使用，以及对 hci_h4_sm 相关接口源码的分析，大概明白了这是一个小的状态机，用于判断逐段接收数据时的包状态。hci_h4_sm 其实是官方提供的一个类似保证包完整性的东西，用于判断一帧完整的 HCI 数据包，并且提供组包完成回调函数的机制。也一定程度上能保证 UART 传输时，可能遇到的一些错误的包组合吧，以免发生传递错误 HCI 包的问题。

**Comment by Yanlineng** [comment]
之前官方文档中对 HCI 层 4个传输接口无论在哪一端都需要完整实现：
ble_transport_to_hs_evt_imp 和 ble_transport_to_hs_acl_impl 都在 ble_hs.c 中具体实现了， 而 ble_transport_to_ll_cmd_impl 和 ble_transport_to_ll_acl_impl 在 ble_ll.c 中具体实现了。

无论缺少 host 或者 controller 中的哪一侧，都需要把未实现的接口完整实现。

**Comment by Yanlineng** [comment]
之前官方文档中对 HCI 层 4个传输接口无论在哪一端都需要完整实现：
ble_transport_to_hs_evt_imp 和 ble_transport_to_hs_acl_impl 都在 ble_hs.c 中具体实现了， 而 ble_transport_to_ll_cmd_impl 和 ble_transport_to_ll_acl_impl 在 ble_ll.c 中具体实现了。

无论缺少 host 或者 controller 中的哪一侧，都需要把未实现的接口完整实现。

**Comment by Yanlineng** [comment]
1. NimBLE 目录分析： Host 、Controller、 transport (HCI)
2. HCI 层 需要实现的接口 分析
3. 自带 UART 例程分析

**Comment by Yanlineng** [comment]
https://github.com/Yanlineng/Docs/blob/main/%E5%88%86%E6%9E%90%20NimBLE%20HCI%20%E5%B1%82/NimBLE%20HCI%20%E5%B1%82%E5%88%86%E6%9E%90.md

**Comment by Yanlineng** [comment]
https://club.rt-thread.org/ask/article/35d46365ec589940.html

**Comment by supperthomas** [comment]
@Yanlineng 帮忙添加到文档中心， 新建一个nimble 软件包即可。

**Comment by Yanlineng** [comment]
- [ ] 添加到文档中心， 软件包下新建 nimble 目录

**Comment by Yanlineng** [comment]
- [ ] 添加到文档中心， 软件包下新建 nimble 目录
